"""Vacancies

Revision ID: bb3b8e57fb8f
Revises: 
Create Date: 2024-07-04 13:05:31.686033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3b8e57fb8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_regions_id', table_name='regions')
    op.drop_index('ix_regions_name', table_name='regions')
    op.drop_table('regions')
    op.drop_index('ix_specializations_id', table_name='specializations')
    op.drop_index('ix_specializations_name', table_name='specializations')
    op.drop_table('specializations')
    op.add_column('vacancies', sa.Column('region', sa.String(), nullable=True))
    op.create_index(op.f('ix_vacancies_published_at'), 'vacancies', ['published_at'], unique=False)
    op.drop_column('vacancies', 'area')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vacancies_published_at'), table_name='vacancies')
    op.drop_column('vacancies', 'region')
    op.create_table('specializations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='specializations_pkey')
    )
    op.create_index('ix_specializations_name', 'specializations', ['name'], unique=True)
    op.create_index('ix_specializations_id', 'specializations', ['id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='regions_pkey')
    )
    op.create_index('ix_regions_name', 'regions', ['name'], unique=True)
    op.create_index('ix_regions_id', 'regions', ['id'], unique=False)
    # ### end Alembic commands ###
